# IN THIS NOTEBOOK WE GONNA BUILD A SINGLE NEURAL NETWORK USING PYTORCH

In [2]:
# LET'S FIRST IMPORT PYTORCH
import torch

In [12]:
# Defining an activation function(sigmoid activation function)

def activation_func(x):
    """
    This a sigmoid activation function
    """
    
    return 1/(1+torch.exp(-x))

In [13]:
# Let's generate some random data
# First setting up the random seed
torch.manual_seed(7)
# Defining our features
features = torch.randn((1, 5))
# Defining the True weights
weights =  torch.rand_like(features)
# Defining true bias term
bias = torch.randn((1,1))


In [6]:
weights = weights.view(5, 1)

In [7]:
torch.mm(features, weights)

tensor([[1.3592]])

In [16]:
# Finding the label y

y = activation_func(torch.sum(features*weights)+bias)
y = activation_func((features*weights).sum()+bias)

In [17]:
y

tensor([[0.6140]])

In [18]:
# Other way to find y

y = activation_func(torch.mm(features, weights.view(5, 1))+bias)

In [19]:
y

tensor([[0.6140]])

In [20]:
features.shape[1]

5

# PUTTING ALL TOGETHER

In [21]:
# Let's generate some random data
# Setting up the random seed
torch.manual_seed(7)
# Defining our features
features = torch.randn((1, 5))
# Define the size of the layers in our network
# Number of input units
n_input = features.shape[1]
# Number of hidden units
n_hidden = 2
# Number of output units
n_output = 1

# Weights for inputs to hidden layer
w1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer
w2 = torch.randn(n_hidden, n_output)

# Setting up the bias for hidden and output layers
b1 = torch.randn((1, n_hidden))
b2 = torch.randn((1, n_output))

Result1 =  activation_func(torch.mm(features, w1)+ b1)
output = activation_func(torch.mm(Result1, w2) + b2)
print(output)

tensor([[0.9940]])
